[tool.poetry]
name = "WXHTMLWidgets"
version = "0.1.1"
description = ""
authors = ["JessicaTegner <jessica.tegner@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
wxPython = "^4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
